#!use/bin/perl
$cmd1 ="grep 'unhealthyChecks\"' webdata.txt > cutdata.txt";
$cmd2 ="sed -i -e \$'s/},{/\\\n/g' cutdata.txt";
$cmd3 ="sed -i 's/\"/ /g' cutdata.txt";
$cmd4 ="sed -i 's/{/\\n/g' cutdata.txt";
$cmd5 ="sed -i 's/unhealthyEntities.*//g' cutdata.txt";
$cmd6 ="sed -i 's/entityId ://g' cutdata.txt";
$cmd7 ="sed -i 's/ , /,/g' cutdata.txt";
$cmd8 ="sed -i 's/ : /:/g' cutdata.txt";
$cmd9 ="sed -i 's/-/#/2' cutdata.txt";
$cmd10 ="sed -i 's/,/|@/1' cutdata.txt";
$cmd11 ="sed -i 's/#.*|//' cutdata.txt";
$cmd12 ="sed -i 's/\@health//g' cutdata.txt";
$cmd13 ="sed -i 's/,name//g' cutdata.txt";
$cmd14 ="sed -i 's/\\n/\\n/g' cutdata.txt";
$cmd14a ="sed -i 's/clusterName.*//g' cutdata.txt;";
$cmd15 ="sed -i '1,2d' cutdata.txt";
$cmd15a ="sed -i 's/}//g' cutdata.txt";
$cmd15b ="sed -i 's/,//g' cutdata.txt";
$cmd15c ="sed -i 's/]//g' cutdata.txt";
$cmd16 ="cat cutdata.txt | sort | uniq -u > final_cutdata.txt";
system ("$cmd1");
system ("$cmd2");
system ("$cmd3");
system ("$cmd4");
system ("$cmd5");
system ("$cmd6");
system ("$cmd7");
system ("$cmd8");
system ("$cmd9");
system ("$cmd10");
system ("$cmd11");
system ("$cmd12");
system ("$cmd13");
system ("$cmd14");
system ("$cmd14a");
system ("$cmd15");
system ("$cmd15a");
system ("$cmd15b");
system ("$cmd15c");
system ("$cmd16");